name: Remove contents files from S3 bucket
description: |
  S3 バケット内のコンテンツファイルを削除します。
inputs:
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  bucket_name:
    description: "The name of the S3 bucket"
    required: true
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Remove contents files from S3 bucket
      shell: bash
      run: | # バケットがない場合などエラーが発生しても後続に続けるため if 文で処理
        if aws s3 rm s3://${{ inputs.bucket_name }} --recursive; then
          echo "Succeeded to remove contents files from S3 bucket"
        else
          echo "Failed to remove contents files from S3 bucket"
        fi
