name: "Deploy Node.js application to cloudfront"
description: |
  npm run build でビルドし、成果物を S3 にアップロードして Cloudfront のキャッシュを無効化します。
inputs:
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory"
    required: true
  dir_build_result:
    description: "Directory where build result is stored"
    required: true
  distribution_id:
    description: "Cloudfront distribution id"
    required: true
  origin_bucket:
    description: "S3 bucket name"
    required: true

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Build
      working-directory: ${{ inputs.dir }}
      run: npm run build
      shell: bash
    - name: Upload to S3
      working-directory: ${{ inputs.dir_build_result }}
      run: aws s3 sync . s3://${{ inputs.origin_bucket }} --delete
      shell: bash
    - name: Invalidate cache
      run: aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution_id }} --paths "/*"
      shell: bash
