name: Add label to issue
description: "Add label to issue"
inputs:
  name:
    description: "The name of the label to add to the issue"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['${{ inputs.name }}']
          })
