name: Comment destroy
description: "Comment that terraform destroy has been executed"
runs:
  using: "composite"
  steps:
    - name: Comment
      uses: ./.github/actions/commons/comment
      with:
        message: "Preview has destroyed."
