name: "Run terraform apply"
description: "Run terraform apply"
inputs:
  args_apply:
    description: "Arguments for terraform apply"
    default: ""
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory for terraform"
  need_tfcmt:
    description: "If true, install tfcmt"
    default: "false"
  token:
    description: "GitHub token, required if need_tfcmt is true"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Terraform apply auto with tfcmt
      if: ${{ inputs.need_tfcmt == 'true' }}
      run: tfcmt apply -- terraform apply -auto-approve ${{ inputs.args_apply }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.dir }}
      shell: bash
    - name: Terraform apply auto without tfcmt
      if: ${{ inputs.need_tfcmt != 'true' }}
      run: terraform apply -auto-approve ${{ inputs.args_apply }}
      working-directory: ${{ inputs.dir }}
      shell: bash
