name: "Upload docker image to ECR"
description: |
  tag_local というイメージを Amazon ECR に tag_remote というタグでプッシュします。
inputs:
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    required: true
  repository_name:
    description: "Repository name"
  tag_local:
    description: "Tagged to local docker image"
  tag_remote:
    description: "Tag to remote docker image"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Login to Amazon ECR
      id: login
      uses: aws-actions/amazon-ecr-login@v2
    - name: Push image to Amazon ECR
      env:
        ECR: ${{ steps.login.outputs.registry }}
        REPO: ${{ inputs.repository_name }}
        TAG: ${{ inputs.tag_remote }}
      run: |
        docker tag ${{ inputs.tag_local }} $ECR/$REPO:$TAG
        docker push $ECR/$REPO:$TAG
      shell: bash
