name: Remove label from issue
description: Remove label from issue
inputs:
  name:
    description: "The name of the label to remove from the issue"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.removeLabel({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "${{ inputs.name }}"
          })
