name: "Install terraform binary, then init"
description: |
  Terraform をインストールし、 init を実行します。
inputs:
  args_init:
    description: "Arguments for terraform init"
    default: ""
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory for terraform"
  need_tfcmt:
    description: "If true, install tfcmt"
    default: "false"
  version_tfcmt:
    description: "Version of tfcmt"
    default: "v4.9.0"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      run: terraform init ${{ inputs.args_init }}
      working-directory: ${{ inputs.dir }}
      shell: bash
    - name: Install tfcmt if need_tfcmt is true
      if: ${{ inputs.need_tfcmt == 'true' }}
      run: |
        sudo curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/$TFCMT_VERSION/tfcmt_linux_amd64.tar.gz
        sudo tar -C /usr/bin -xzf ./tfcmt.tar.gz
      env:
        TFCMT_VERSION: ${{ inputs.version_tfcmt }}
      shell: bash
