name: "Run terraform plan"
description: "Run terraform plan"
inputs:
  args_plan:
    description: "Arguments for terraform plan"
    default: ""
  aws_region:
    description: "The AWS region"
    default: "ap-northeast-1"
  aws_role:
    description: "The AWS role ARN"
    default: ""
  dir:
    description: "Working directory for terraform"
  label:
    description: "Label of the environment"
    default: "dev/infrastructure"
    required: false
  need_tfcmt:
    description: "If true, install tfcmt"
    default: "false"
  token:
    description: "GitHub token, required if need_tfcmt is true"
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_role != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: ${{ inputs.aws_region }}
    - name: Terraform plan with tfcmt
      if: ${{ inputs.need_tfcmt == 'true' }}
      run: tfcmt -var "target:${{ inputs.label }}" plan -- terraform plan -no-color -input=false ${{ inputs.args_plan }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.dir }}
      shell: bash
    - name: Terraform plan without tfcmt
      if: ${{ inputs.need_tfcmt != 'true' }}
      run: terraform plan -no-color -input=false ${{ inputs.args_plan }}
      working-directory: ${{ inputs.dir }}
      shell: bash
