name: "Build docker image"
description: |
  ディレクトリ dir で Docker イメージをビルドし、必要ならテストを実行します。
inputs:
  dir:
    description: "Working directory for docker"
  tag:
    description: "Tag to docker image"
  test_commands:
    description: "Test commands for docker image if need"
    default: ""
runs:
  using: "composite"
  steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.dir }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Build image
      working-directory: ${{ inputs.dir }}
      run: docker build -t ${{ inputs.tag }} .
      shell: bash
    - name: Test image
      if: "${{ inputs.test_commands != '' }}"
      env:
        CMD: ${{ inputs.test_commands }}
        TAG: ${{ inputs.tag }}
      run: docker run --rm --entrypoint= $TAG $CMD
      shell: bash
