name: common-check
run-name: Common check codes for "${{ github.head_ref }}@${{ github.event.pull_request.head.sha }}"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

env:
  AWS_REGION: ap-northeast-1
  DIR_ACCOUNT_BACKEND: account/backend
  DIR_ACCOUNT_FRONTEND: account/frontend
  DIR_LOG: log
  DIR_LOG_BACKEND: log/backend

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      common_terraform_dev: ${{ steps.filter.outputs.common_terraform_dev }}
      common_terraform_stg: ${{ steps.filter.outputs.common_terraform_stg }}
      common_terraform_prod: ${{ steps.filter.outputs.common_terraform_prod }}
      account_terraform_dev: ${{ steps.filter.outputs.account_terraform_dev }}
      account_terraform_stg: ${{ steps.filter.outputs.account_terraform_stg }}
      account_terraform_prod: ${{ steps.filter.outputs.account_terraform_prod }}
      account_backend: ${{ steps.filter.outputs.account_backend }}
      account_frontend: ${{ steps.filter.outputs.account_frontend }}
      log_terraform_dev: ${{ steps.filter.outputs.log_terraform_dev }}
      log_terraform_stg: ${{ steps.filter.outputs.log_terraform_stg }}
      log_terraform_prod: ${{ steps.filter.outputs.log_terraform_prod }}
      log_backend: ${{ steps.filter.outputs.log_backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/changes
        id: filter

  account_frontend_test:
    needs: [changes]
    if: needs.changes.outputs.account_frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/node_install
        with:
          dir: ${{ env.DIR_ACCOUNT_FRONTEND }}
          version: "18"
      - uses: ./.github/actions/commons/node_test
        with:
          dir: ${{ env.DIR_ACCOUNT_FRONTEND }}
          need_comment: "true"

  account_frontend_lint:
    needs: [changes]
    if: needs.changes.outputs.account_frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/node_install
        with:
          dir: ${{ env.DIR_ACCOUNT_FRONTEND }}
          version: "18"
      - uses: ./.github/actions/commons/node_lint
        with:
          dir: ${{ env.DIR_ACCOUNT_FRONTEND }}

  account_backend_lint:
    needs: [changes]
    if: needs.changes.outputs.account_backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/python_install
        with:
          dir: ${{ env.DIR_ACCOUNT_BACKEND }}
          version: "3.11"
          version_poetry: "1.8.2"
      - uses: ./.github/actions/commons/python_lint
        with:
          dir: ${{ env.DIR_ACCOUNT_BACKEND }}

  account_backend_test:
    needs: [changes]
    if: needs.changes.outputs.account_backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/python_install
        with:
          dir: ${{ env.DIR_ACCOUNT_BACKEND }}
          version: "3.11"
          version_poetry: "1.8.2"
      - uses: ./.github/actions/commons/python_test
        with:
          dir: ${{ env.DIR_ACCOUNT_BACKEND }}
          need_comment: "true"

  log_backend_lint:
    needs: [changes]
    if: needs.changes.outputs.log_backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/python_install
        with:
          dir: ${{ env.DIR_LOG }}
          version: "3.11"
          version_poetry: "1.8.2"
      - uses: ./.github/actions/commons/python_lint
        with:
          dir: ${{ env.DIR_LOG }}
          targets: "backend/src backend/tests"

  log_backend_test:
    needs: [changes]
    if: needs.changes.outputs.log_backend == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: log
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/commons/python_install
        with:
          dir: ${{ env.DIR_LOG }}
          version: "3.11"
          version_poetry: "1.8.2"
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: ${{ env.DIR_LOG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check by pytest on backend
        id: pytest
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: "dummy" # AWS アクセス情報がダミーでも必要なので定義。実際にはアクセスしない。
          AWS_SECRET_ACCESS_KEY: "dummy"
          AWS_SECURITY_TOKEN: "dummy"
          AWS_SESSION_TOKEN: "dummy"
        run: |
          set -o pipefail
          cd ..
          docker compose up -d --wait || echo $?
          cd backend
          poetry run pytest --cov=src --cov-branch --cov-report=term-missing:skip-covered --junitxml=pytest.xml tests | tee pytest-coverage.txt
          cd ..
          docker compose down
        working-directory: ${{ env.DIR_LOG_BACKEND }}
      - name: Comment coverage on Pull-Request
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Coverage detail
          badge-title: Coverage
          coverage-path-prefix: ${{ env.DIR_LOG_BACKEND }}
          create-new-comment: true
          pytest-coverage-path: ${{ env.DIR_LOG_BACKEND }}/pytest-coverage.txt
          junitxml-path: ${{ env.DIR_LOG_BACKEND }}/pytest.xml
          junitxml-title: Coverage for "${{ env.DIR_LOG_BACKEND }}"
      - name: Error Handling
        if: ${{ steps.pytest.outcome == 'failure' }}
        run: |
          echo "Error handling"
          echo ${{ steps.pytest.outcome }}
          exit 1

  terraform_plan_dev:
    needs: [changes]
    if: |
      ${{ needs.changes.outputs.common_terraform_dev == 'true' }} ||
      ${{ needs.changes.outputs.account_terraform_dev == 'true' }} ||
      ${{ needs.changes.outputs.log_terraform_dev == 'true' }}
    uses: ./.github/workflows/reusable-terraform-plan.yml
    permissions: write-all
    with:
      aws_region: ap-northeast-1
      aws_role: arn:aws:iam::082954585471:role/gha-test-infrastructure-role-dev
      ignore_account_api_changes: false
      need_account: ${{ needs.changes.outputs.account_terraform_dev == 'true' }}
      need_common: ${{ needs.changes.outputs.common_terraform_dev == 'true' }}
      need_log: ${{ needs.changes.outputs.log_terraform_dev == 'true' }}
      stage: dev

  terraform_plan_stg:
    needs: [changes]
    if: |
      ${{ needs.changes.outputs.common_terraform_stg == 'true' }} ||
      ${{ needs.changes.outputs.account_terraform_stg == 'true' }} ||
      ${{ needs.changes.outputs.log_terraform_stg == 'true' }}
    uses: ./.github/workflows/reusable-terraform-plan.yml
    permissions: write-all
    with:
      aws_region: ap-northeast-1
      aws_role: arn:aws:iam::082954585471:role/gha-test-infrastructure-role-dev
      ignore_account_api_changes: true
      need_account: ${{ needs.changes.outputs.account_terraform_stg == 'true' }}
      need_common: ${{ needs.changes.outputs.common_terraform_stg == 'true' }}
      need_log: ${{ needs.changes.outputs.log_terraform_stg == 'true' }}
      stage: stg

  terraform_plan_prod:
    needs: [changes]
    if: |
      ${{ needs.changes.outputs.common_terraform_prod == 'true' }} ||
      ${{ needs.changes.outputs.account_terraform_prod == 'true' }} ||
      ${{ needs.changes.outputs.log_terraform_prod == 'true' }}
    uses: ./.github/workflows/reusable-terraform-plan.yml
    permissions: write-all
    with:
      aws_region: ap-northeast-1
      aws_role: arn:aws:iam::082954585471:role/gha-test-infrastructure-role-dev
      ignore_account_api_changes: true
      need_account: ${{ needs.changes.outputs.account_terraform_prod == 'true' }}
      need_common: ${{ needs.changes.outputs.common_terraform_prod == 'true' }}
      need_log: ${{ needs.changes.outputs.log_terraform_prod == 'true' }}
      stage: prod

  check_code:
    needs:
      - account_backend_lint
      - account_backend_test
      - account_frontend_lint
      - account_frontend_test
      - log_backend_lint
      - log_backend_test
      - terraform_plan_dev
      - terraform_plan_stg
      - terraform_plan_prod
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Force failure
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: echo "Failed or canceled" && exit 1
      - run: echo "$json"
        env:
          json: ${{ toJSON(needs) }}
